### ISSUE TITLE
The request failed "Access Denied"

### ISSUE THREAD

**Issue by Konstantin2073** [Froren/realtorca#37]
Good afternoon.
Problem.

The request worked stopped working from 18-07-2022 (the request has been running since 2017)

PHP Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error response [url] https://api37.realtor.ca/Listing.svc/PropertySearch [status code] 403 [reason phrase] Forbidden'

Request from POSTMAN
gives :
Access Denied
error 15
api37.realtor.ca
2022-07-22 10:12:42 UTC
(
https://api37.realtor.ca/_Incapsula_Resource?CWUDNSAI=23&xinfo=12-41705013-0%20NNNN%20RT%281658483914883%2018%29%20q%280%20-1%20-1%208%29%20r% 280%20-1%29%20B15%2814%2c0%2c0%29%20U5&incident_id=729000760091225407-206337989953524492&edet=15&cinfo=0e0000008a09&rpinfo=0&mth=POST
)

**Comment by kris-dgen-solutions** [comment]
Seeing the same problem

Let me know if there is a fix found

**Comment by mcgeddes11** [comment]
From what I can tell they updated the API domain and added some very easily spoofable headers.  I think the new domain is:
`api2.realtor.ca` instead of `api37.realtor.ca`.

The headers that I used for the search request are:
`{"Referer": "https://www.realtor.ca/", "Origin": "https://www.realtor.ca/", "Host": "api2.realtor.ca"}`

I haven't tested the listing details endpoint, but this seems to work for me

**Comment by kris-dgen-solutions** [comment]
@mcgeddes11 You got it right - tested and confirmed!

So this issue is resolved, just change the URL to api2 and add the headers defined by @mcgeddes11

**Comment by Konstantin2073** [comment]
Thanks a lot.
The headers helped.
Works.

**Comment by Konstantin2073** [comment]
Very strange - it worked once, subsequent launches again 403 [reason phrase] Forbidden.

**Comment by mcgeddes11** [comment]
Yeah, can confirm I'm seeing the same thing. Can run a handful of queries against the endpoint then it returns a 403. Might be down to rate-throttling or some cookies that are expiring. Sadly, debugging both of those is a good chunk above my paygrade.

**Comment by harishandorid** [comment]
on nodejs iam getting like using api2
"<html style=\"height:100%\"><head><META NAME=\"ROBOTS\" CONTENT=\"NOINDEX, NOFOLLOW\"><meta name=\"format-detection\" content=\"telephone=no\"><meta name=\"viewport\" content=\"initial-scale=1.0\"><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\"><script src=\"/eu-Leaftle-He-cut-taking-Wealt-now-and-To-ping-w\" async></script></head><body style=\"margin:0px;height:100%\"><iframe id=\"main-iframe\" src=\"/_Incapsula_Resource?CWUDNSAI=23&xinfo=14-39767672-0%20NNNN%20RT%281667189894779%2023%29%20q%280%20-1%20-1%20-1%29%20r%280%20-1%29%20B15%2814%2c0%2c0%29%20U5&incident_id=1167000870122793444-221978611606820302&edet=15&cinfo=0e0000001e24&rpinfo=0&mth=POST\" frameborder=0 width=\"100%\" height=\"100%\" marginheight=\"0px\" marginwidth=\"0px\">Request unsuccessful. Incapsula incident ID: 1167000870122793444-221978611606820302</iframe></body></html>"

**Comment by harishandorid** [comment]
please help api is not working for me. i have checked with postman one time it shows empty results then i am getting like this
<html style="height:100%">

<head>
	<META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">
	<meta name="format-detection" content="telephone=no">
	<meta name="viewport" content="initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<script type="text/javascript" src="/_Incapsula_Resource?SWJIYLWA=719d34d31c8e3a6e6fffd425f7e032f3"></script>
	<script src="/eu-Leaftle-He-cut-taking-Wealt-now-and-To-ping-w" async></script>
</head>

<body style="margin:0px;height:100%"><iframe id="main-iframe"
		src="/_Incapsula_Resource?CWUDNSAI=23&xinfo=13-89114503-0%200NNN%20RT%281667191643325%2082%29%20q%280%20-1%20-1%20-1%29%20r%280%20-1%29%20B14%283%2c901868%2c0%29%20U5&incident_id=1044000790387347646-469604212315263949&edet=14&cinfo=03000000&rpinfo=0&mth=POST"
		frameborder=0 width="100%" height="100%" marginheight="0px" marginwidth="0px">Request unsuccessful. Incapsula
		incident ID: 1044000790387347646-469604212315263949</iframe></body>

</html>

**Comment by harishandorid** [comment]
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html
	PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<script src="/eu-Leaftle-He-cut-taking-Wealt-now-and-To-ping-w" async></script>
	<title>Service</title>
	<style>
		BODY {
			color: #000000;
			background-color: white;
			font-family: Verdana;
			margin-left: 0px;
			margin-top: 0px;
		}

		#content {
			margin-left: 30px;
			font-size: .70em;
			padding-bottom: 2em;
		}

		A:link {
			color: #336699;
			font-weight: bold;
			text-decoration: underline;
		}

		A:visited {
			color: #6699cc;
			font-weight: bold;
			text-decoration: underline;
		}

		A:active {
			color: #336699;
			font-weight: bold;
			text-decoration: underline;
		}

		.heading1 {
			background-color: #003366;
			border-bottom: #336699 6px solid;
			color: #ffffff;
			font-family: Tahoma;
			font-size: 26px;
			font-weight: normal;
			margin: 0em 0em 10px -20px;
			padding-bottom: 8px;
			padding-left: 30px;
			padding-top: 16px;
		}

		pre {
			font-size: small;
			background-color: #e5e5cc;
			padding: 5px;
			font-family: Courier New;
			margin-top: 0px;
			border: 1px #f0f0e0 solid;
			white-space: pre-wrap;
			white-space: -pre-wrap;
			word-wrap: break-word;
		}

		table {
			border-collapse: collapse;
			border-spacing: 0px;
			font-family: Verdana;
		}

		table th {
			border-right: 2px white solid;
			border-bottom: 2px white solid;
			font-weight: bold;
			background-color: #cecf9c;
		}

		table td {
			border-right: 2px white solid;
			border-bottom: 2px white solid;
			background-color: #e5e5cc;
		}
	</style>
</head>

<body>
	<div id="content">
		<p class="heading1">Service</p>
		<p>Method not allowed.</p>
	</div>
	<script async type="text/javascript"
		src="/_Incapsula_Resource?SWJIYLWA=719d34d31c8e3a6e6fffd425f7e032f3&ns=4&cb=427683774"></script>
</body>

</html>

**Comment by windowshopr** [comment]
I think I'm getting an error similar to @harishandorid. Not sure where the headers mentioned previously should get implemented if that's the way to fix it, so maybe someone can shed some light on that for me to try.

I'm running Node v16.17.1 on Windows 10. I've created a `main.js` file that I run with `node main.js`, which looks like this (some time has been spent on the comments for others ease of use):

```
const realtor = require('./realtorca');

let opts = {
    CultureId: 1, // language identifier, 1 for English, 2 for French. Defaults to 1.
    ApplicationId: 37, // Mandatory for some endpoints, defaults to 37, their mobile app uses the value 37
    PropertySearchTypeId: 1, //Defaulted to 1. Determines the type of property, possible values:
                             // 0 No Preference
                             // 1 Residential
                             // 2 Recreational
                             // 3 Condo/Strata
                             // 4 Agriculture
                             // 5 Parking
                             // 6 Vacant Land
                             // 8 Multi Family
    HashCode: 0, // Mandatory for some endpoints; their mobile app defaults it to 0
    PriceMin: 25000,
    PriceMax: 200000,
    LongitudeMin: -140.80078, // All of Canada
    LongitudeMax: -57.83203,
    LatitudeMin: 43.50872,
    LatitudeMax: 63.81644,
    //BuildingAgeMin: 2000,
    //BuildingAgeMax: 2023,
    TransactionTypeId: 2, // Defaults to 2?
                          // 1 For sale or rent
                          // 2 For sale
                          // 3 For rent
    //StoreyRange: "0-2", // - "min-max" i.e. "2-3"
    BedRange: "1-0", // "min-max" if min = max, it searches for the exact value. If it's 1-0, it means it's 1+. Maxes at 5
    BathRange: "1-0",
    //SortBy: "price", // How to sort (e.g. price, date, etc)
    SortOrder: "1-D", // How to order the items after sorting them by a given field (e.g. ascending, descending)
                      // Type	Sort
                      // Low to High ($)	1-A
                      // High to Low ($)	1-D
                      // Date Posted: New to Old	6-D
                      // Date Posted: Old to New	6-A
                      // Open Houses First	12-D
                      // More Photos First	13-D
                      // Virtual Tour First	11-D
    //organizationID: , // sort/search by organizationID of a group of realtors. Value of this field can be found using a URL such as https://www.realtor.ca/Residential/OfficeDetails.aspx?OrganizationId=271479 as pointed out by Froren.
    //individualID: , //sort/search by agentID. Can be found using a URL such as https://www.realtor.ca/Agent/1914698/Gaetan-Kill-130---1152-Main... (in this case individualID = 1914698) as indicated by Kris.
    //viewState: m, // m, g, or 1. Seems irrelevant.
    Longitude: 50.445210, // (Optional) Longitude of the current user's location
    Latitude: -104.618896, // (Optional) Latitude of the current user's location
    ZoomLevel: 4, // not sure what this does: UPDATE This is how far zoomed in/out you are on the map, 1 is all the way out, (maybe) 21 is all the way in
    //CurrentPage: 1, // read somewhere that it maxes at 51
    RecordsPerPage: 500, // their mobile app uses 500 as the default value
    //MaximumResults: 500, 
    //PropertyTypeGroupID:, // ???
    OwnershipTypeGroupId: 0, // 0 Any
                             // 1 Freehold
                             // 2 Condo/Strata
                             // 3 Timeshare/Fractional
                             // 4 Leasehold
    ViewTypeGroupId: 0, // 0 Any
                        // 1 City
                        // 2 Mountain
                        // 3 Ocean
                        // 4 Lake
                        // 5 River
                        // 6 Ravine
                        // 7 Other
                        // 8 All Water Views
    BuildingTypeId: 0, // 0 Any
                       // 1 House
                       // 2 Duplex
                       // 3 Triplex
                       // 5 Residential Commercial Mix
                       // 6 Mobile Home
                       // 12 Special Purpose
                       // 14 Other
                       // 16 Row/Townhouse
                       // 17 Apartment
                       // 19 Fourplex
                       // 20 Garden Home
                       // 27 Manufactured Home/Mobile
                       // 28 Commercial Apartment
                       // 29 Manufactured Home
    ConstructionStyleId: 0, // 0 Any
                            // 1 Attached
                            // 3 Detached
                            // 5 Semi-detached
                            // 7 Stacked
                            // 9 Link
    //UnitRange: "2-0", // how many units within a given building, similar to BathRange, such as 2-0 to denote 2 or more units
    //AirCondition: 0, // 0 or 1, defaults 0
    // Pool: 0, // 0 or 1, defaults 0
    // Fireplace: 0, // 0 or 1, defaults 0
    // Garage: 0, // 0 or 1, defaults 0
    // Waterfront: 0, // - 0 or 1, defaults 0
    // Acreage: 0, // - 0 or 1, defaults 0
    // Keywords: "", // - search text
    // ListingIds: , // - Comma Separated listing Ids to scope the search to
    // ReferenceNumber: , // - Search using MLS #, this is required for viewing a listing detail
    // OpenHouse: 0, // - 0 or 1, must include if filtering by open house
    // OpenHouseStartDate: , // - MM/DD/YYYY
    // OpenHouseEndDate: , // - MM/DD/YYYY

};

console.log(realtor.buildUrl(opts));

// Parse options from url
//console.log(realtor.optionsFromUrl("https://www.realtor.ca/Residential/Map.aspx#LongitudeMin=-79.6758985519409&LongitudeMax=-79.6079635620117&LatitudeMin=43.57601549736786&LatitudeMax=43.602250137362276&PriceMin=100000&PriceMax=425000"));

realtor.post(opts)
    .then(data => {
        //json response
        console.log("####################################### THE RESULTS #######################################")
        console.log(JSON.stringify(data))
        console.log("####################################### THE RESULTS #######################################")
    })
    .catch(err => {
        console.log(err)
    });
```

You can look through the variables I've used in the search, but basically looking for any residential, priced 25,000 - 200,000, in all of Canada, 1+ bed and 1+ bath.

This attempt results in the following full output. Ideas?:

```
https://www.realtor.ca/Residential/Map.aspx#CultureId=1&ApplicationId=37&PropertySearchTypeId=1&HashCode=0&PriceMin=25000&PriceMax=200000&LongitudeMin=-140.80078&LongitudeMax=-57.83203&LatitudeMin=43.50872&LatitudeMax=63.81644&TransactionTypeId=2&BedRange=1-0&BathRange=1-0&SortOrder=1-D&ZoomLevel=4&CurrentPage=1&RecordsPerPage=500&OwnershipTypeGroupId=0&ViewTypeGroupId=0&BuildingTypeId=0&ConstructionStyleId=0

StatusCodeError: 403 - "<html style=\"height:100%\"><head><META NAME=\"ROBOTS\" CONTENT=\"NOINDEX, NOFOLLOW\"><meta name=\"format-detection\" content=\"telephone=no\"><meta name=\"viewport\" content=\"initial-scale=1.0\"><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\"><script src=\"/eu-Leaftle-He-cut-taking-Wealt-now-and-To-ping-w\" async></script></head><body style=\"margin:0px;height:100%\"><iframe id=\"main-iframe\" src=\"/_Incapsula_Resource?CWUDNSAI=23&xinfo=14-1657609727-0%20NNNN%20RT%281673584418079%2041%29%20q%280%20-1%20-1%20-1%29%20r%280%20-1%29%20B15%2814%2c0%2c0%29%20U5&incident_id=1445000431162217037-7030996763706460878&edet=15&cinfo=0e0000000e24&rpinfo=0&mth=POST\" frameborder=0 width=\"100%\" height=\"100%\" marginheight=\"0px\" marginwidth=\"0px\">Request unsuccessful. Incapsula incident ID: 1445000431162217037-7030996763706460878</iframe></body></html>"
    at new StatusCodeError (I:\nasty\NodeJS_Projects\realtorca\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (I:\nasty\NodeJS_Projects\realtorca\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (I:\nasty\NodeJS_Projects\realtorca\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (I:\nasty\NodeJS_Projects\realtorca\node_modules\request\request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (I:\nasty\NodeJS_Projects\realtorca\node_modules\request\request.js:1154:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (I:\nasty\NodeJS_Projects\realtorca\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  statusCode: 403,
  error: '<html style="height:100%"><head><META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW"><meta name="format-detection" content="telephone=no"><meta name="viewport" content="initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><script src="/eu-Leaftle-He-cut-taking-Wealt-now-and-To-ping-w" async></script></head><body style="margin:0px;height:100%"><iframe id="main-iframe" src="/_Incapsula_Resource?CWUDNSAI=23&xinfo=14-1657609727-0%20NNNN%20RT%281673584418079%2041%29%20q%280%20-1%20-1%20-1%29%20r%280%20-1%29%20B15%2814%2c0%2c0%29%20U5&incident_id=1445000431162217037-7030996763706460878&edet=15&cinfo=0e0000000e24&rpinfo=0&mth=POST" frameborder=0 width="100%" height="100%" marginheight="0px" marginwidth="0px">Request unsuccessful. Incapsula incident ID: 1445000431162217037-7030996763706460878</iframe></body></html>',
  options: {
    method: 'POST',
    uri: 'https://api2.realtor.ca/Listing.svc/PropertySearch_Post',
    form: {
      CultureId: 1,
      ApplicationId: 37,
      PropertySearchTypeId: 1,
      HashCode: 0,
      PriceMin: 25000,
      PriceMax: 200000,
      LongitudeMin: -140.80078,
      LongitudeMax: -57.83203,
      LatitudeMin: 43.50872,
      LatitudeMax: 63.81644,
      TransactionTypeId: 2,
      BedRange: '1-0',
      BathRange: '1-0',
      SortOrder: '1-D',
      ZoomLevel: 4,
      CurrentPage: 1,
      RecordsPerPage: 500,
      OwnershipTypeGroupId: 0,
      ViewTypeGroupId: 0,
      BuildingTypeId: 0,
      ConstructionStyleId: 0
    },
    json: true,
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: <ref *1> IncomingMessage {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      constructed: true,
      sync: true,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      destroyed: true,
      errored: null,
      closed: true,
      closeEmitted: true,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: true,
      dataEmitted: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    _events: [Object: null prototype] {
      end: [Array],
      close: [Array],
      data: [Function (anonymous)],
      error: [Function (anonymous)]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api2.realtor.ca',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api2.realtor.ca',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 9,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: false,
      [Symbol(kSetKeepAliveInitialDelay)]: 0,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: true,
    rawHeaders: [
      'Content-Type',
      'text/html',
      'Cache-Control',
      'no-cache',
      'Connection',
      'close',
      'Content-Length',
      '841',
      'X-Iinfo',
      '14-1657609727-0 NNNN RT(1673584418079 41) q(0 -1 -1 -1) r(0 -1) B15(14,0,0) U5',
      'Set-Cookie',
      'visid_incap_2271082=VLTSzqanTHiXlwjTTsuVFyLfwGMAAAAAQUIPAAAAAAAjSdT3dQZ0ALAFj94VFc+j; expires=Fri, 12 Jan 2024 06:17:55 GMT; HttpOnly; path=/; Domain=.realtor.ca',
      'Set-Cookie',
      'incap_ses_1445_2271082=gwc6T1D5I0WGfbh3PKwNFCLfwGMAAAAAA1nObdZkKQlH0Sr/1wJ58w==; path=/; Domain=.realtor.ca'
    ],
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: '',
    method: null,
    statusCode: 403,
    statusMessage: 'Forbidden',
    client: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api2.realtor.ca',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api2.realtor.ca',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 9,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: false,
      [Symbol(kSetKeepAliveInitialDelay)]: 0,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _consuming: false,
    _dumped: false,
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /Listing.svc/PropertySearch_Post HTTP/1.1\r\n' +
        'host: api2.realtor.ca\r\n' +
        'content-type: application/x-www-form-urlencoded\r\n' +
        'accept: application/json\r\n' +
        'content-length: 368\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/Listing.svc/PropertySearch_Post',
      _ended: true,
      res: [Circular *1],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api2.realtor.ca',
      protocol: 'https:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null
    },
    request: Request {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      method: 'POST',
      uri: [Url],
      readable: true,
      writable: true,
      explicitMethod: true,
      _qs: [Querystring],
      _auth: [Auth],
      _oauth: [OAuth],
      _multipart: [Multipart],
      _redirect: [Redirect],
      _tunnel: [Tunnel],
      _rp_resolve: [Function (anonymous)],
      _rp_reject: [Function (anonymous)],
      _rp_promise: [Promise [Object]],
      _rp_callbackOrig: undefined,
      callback: [Function (anonymous)],
      _rp_options: [Object],
      headers: [Object],
      setHeader: [Function (anonymous)],
      hasHeader: [Function (anonymous)],
      getHeader: [Function (anonymous)],
      removeHeader: [Function (anonymous)],
      localAddress: undefined,
      pool: {},
      dests: [],
      __isRequestRequest: true,
      _callback: [Function: RP$callback],
      proxy: null,
      tunnel: true,
      setHost: true,
      originalCookieHeader: undefined,
      _disableCookies: true,
      _jar: undefined,
      port: 443,
      host: 'api2.realtor.ca',
      body: 'CultureId=1&ApplicationId=37&PropertySearchTypeId=1&HashCode=0&PriceMin=25000&PriceMax=200000&LongitudeMin=-140.80078&LongitudeMax=-57.83203&LatitudeMin=43.50872&LatitudeMax=63.81644&TransactionTypeId=2&BedRange=1-0&BathRange=1-0&SortOrder=1-D&ZoomLevel=4&CurrentPage=1&RecordsPerPage=500&OwnershipTypeGroupId=0&ViewTypeGroupId=0&BuildingTypeId=0&ConstructionStyleId=0',
      path: '/Listing.svc/PropertySearch_Post',
      _json: true,
      httpModule: [Object],
      agentClass: [Function: Agent],
      agent: [Agent],
      _started: true,
      href: 'https://api2.realtor.ca/Listing.svc/PropertySearch_Post',
      req: [ClientRequest],
      ntick: true,
      response: [Circular *1],
      originalHost: 'api2.realtor.ca',
      originalHostHeaderName: 'host',
      responseContent: [Circular *1],
      _destdata: true,
      _ended: true,
      _callbackCalled: true,
      [Symbol(kCapture)]: false
    },
    toJSON: [Function: responseToJSON],
    caseless: Caseless { dict: [Object] },
    body: '<html style="height:100%"><head><META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW"><meta name="format-detection" content="telephone=no"><meta name="viewport" content="initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><script src="/eu-Leaftle-He-cut-taking-Wealt-now-and-To-ping-w" async></script></head><body style="margin:0px;height:100%"><iframe id="main-iframe" src="/_Incapsula_Resource?CWUDNSAI=23&xinfo=14-1657609727-0%20NNNN%20RT%281673584418079%2041%29%20q%280%20-1%20-1%20-1%29%20r%280%20-1%29%20B15%2814%2c0%2c0%29%20U5&incident_id=1445000431162217037-7030996763706460878&edet=15&cinfo=0e0000000e24&rpinfo=0&mth=POST" frameborder=0 width="100%" height="100%" marginheight="0px" marginwidth="0px">Request unsuccessful. Incapsula incident ID: 1445000431162217037-7030996763706460878</iframe></body></html>',
    [Symbol(kCapture)]: false,
    [Symbol(kHeaders)]: {
      'content-type': 'text/html',
      'cache-control': 'no-cache',
      connection: 'close',
      'content-length': '841',
      'x-iinfo': '14-1657609727-0 NNNN RT(1673584418079 41) q(0 -1 -1 -1) r(0 -1) B15(14,0,0) U5',
      'set-cookie': [Array]
    },
    [Symbol(kHeadersCount)]: 14,
    [Symbol(kTrailers)]: null,
    [Symbol(kTrailersCount)]: 0,
    [Symbol(RequestTimeout)]: undefined
  }
}
```
